### ISSUE TITLE
关联依赖工程没有上传，build fail

### ISSUE THREAD

**Issue by liuzhiyi1992** [linshaolie/DynamicUpdateDemo#1]
![image](https://cloud.githubusercontent.com/assets/13046550/23249860/60ab9a5e-f9e1-11e6-83dc-23f3a91173e4.png)

**Comment by linshaolie** [comment]
执行 npm install

**Comment by liuzhiyi1992** [comment]
![image](https://cloud.githubusercontent.com/assets/13046550/23292345/1b2ad17a-fa9a-11e6-969d-f405fe9be74f.png)





and after &npm install
do:
$react-native run-ios
with error:
![image](https://cloud.githubusercontent.com/assets/13046550/23292357/32de97a2-fa9a-11e6-90f6-e69d8b2f4caa.png)

**Comment by linshaolie** [comment]
'RCTBridgeModule.h' file not found 应该是你没执行npm install 的原因，底部 warn_unused_result  的错误，你可以尝试在出错的调用处加上 `(void)` 或 `int unused __attribute__((unused)) = `。然后在Xcode尝试下重新编译

**Comment by duxiwei** [comment]
为什么运行不了？总是提示，Could not connect to development server !!但是我运行其他的程序没有问题！在线等您回答

**Comment by linshaolie** [comment]
@duxiwei 在Xcode编译通过了吗？服务器start 了吗？你是在模拟器跑的还是手机上跑的呢？

**Comment by duxiwei** [comment]
编译通过了，而且服务器也start了

**Comment by linshaolie** [comment]
@duxiwei 我这边没法复现你说的问题，你没有连接vpn什么的吧？能把具体的错误截图吗

**Comment by duxiwei** [comment]
没有连接VPN，这个还需要连接VPN？？？还有版本增量更新可以直接用react写吧，不需要用原生的来实现吧？？？

**Comment by linshaolie** [comment]
不用vpn，是接了vpn可能导致连接不上。是的，每个新的版本需要在 js上进行版本的累加
